version: '3.9'
services:
  asir-apache:
    image: php:7.4-apache
    container_name: asir-apache
    networks:
      proyect1_subnet:
        ipv4_address: 10.0.1.11
    ports:
    - '80:80'
    - '8000:8000'
    volumes:
      - /home/asir2a/Escritorio/SRI/Proyecto1/Apache:/var/www/html/
      - /home/asir2a/Escritorio/SRI/Proyecto1/Apache/confApache:/etc/apache2
      - /home/asir2a/Escritorio/SRI/Proyecto1/Apache/confhttpdconfhttpd:/etc/httpd/conf

  asir_cliente_proyect:
    container_name: asir_cliente_proyect
    image: alpine
    networks:
      proyect1_subnet:
        ipv4_address: 10.0.1.12

    stdin_open: true
    tty: true #docker run -t
    dns:
      - 10.0.1.10 #ip del contenedor DNS

  proyectDNS:
    image: internetsystemsconsortium/bind9:9.16
    container_name: asir_proyectDNS
    networks:
      proyect1_subnet:
        ipv4_address: 10.0.1.10
    ports:
      - 5300:53/udp
      - 5300:53/tcp
    volumes:
      - /home/asir2a/Escritorio/SRI/Proyecto1/DNS/conf:/etc/bind
      - /home/asir2a/Escritorio/SRI/Proyecto1/DNS/zonas:/var/lib/bind
networks:
    proyect1_subnet:
      external: true

