version: '3.9'
services:
  asir-apache:
    image: php:7.4-apache
    container_name: asir-apache
    networks:
      proyect1_subnet:
        ipv4_address: 10.0.1.11
    ports:
    - '80:80'
    - '8000:8000'
    - '443:443'
    volumes:
      - /home/asir2a/Escritorio/SRI/Proyecto1/Apache:/var/www/html/
      - /home/asir2a/Escritorio/SRI/Proyecto1/Apache/confApache:/etc/apache2

  asir_cliente_proyect:
    container_name: asir_cliente_proyect
    image: alpine
    networks:
      proyect1_subnet:
        ipv4_address: 10.0.1.12

    stdin_open: true
    tty: true #docker run -t
    dns:
      - 10.0.1.10 #ip del contenedor DNS

  firefox:
    image: jlesage/firefox
    container_name: asir_firefox
    ports:
      - 5800:5800
    volumes:
      - ./firefox:/config:rw
    dns:
      - 10.0.1.10
    networks:
      proyect1_subnet:
        ipv4_address: 10.0.1.13

  proyectDNS:
    image: internetsystemsconsortium/bind9:9.16
    container_name: asir_proyectDNS
    networks:
      proyect1_subnet:
        ipv4_address: 10.0.1.10
    ports:
      - 5300:53/udp
      - 5300:53/tcp
    volumes:
      - /home/asir2a/Escritorio/SRI/Proyecto1/DNS/conf:/etc/bind
      - /home/asir2a/Escritorio/SRI/Proyecto1/DNS/zonas:/var/lib/bind


  wireshark:
    image: lscr.io/linuxserver/wireshark:latest
    container_name: wireshark
    cap_add:
      - NET_ADMIN
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /path/to/config:/config
    ports:
      - 3000:3000 #optional
    restart: unless-stopped

networks:
  proyect1_subnet:
    external: true