version: '3.9'
services:
  asir-apache:
    image: php:7.4-apache
    container_name: asir-apache
    ports:
    - '8001:80'
    volumes:
      - /home/asir2a/Escritorio/SRI/Proyecto1/Apache:/var/www/html/
      - confApache:/etc/apache2
volumes:
  confApache: